app:
  name: MiniShop
  version: 1.0.0
server:
  port: 5090
  timeout: 30
  environment: development
database:
  mariadb:
    host: localhost
    port: 3306
    user: root
    password:
    dbname: minishop
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_idle_time: 5
    conn_max_lifetime: 60
